version: "3"
services:
  rocky8base:
    build:
      context: .
      args:
        rocky: $RL8
  rocky8docs:
    build:
      context: .
      dockerfile: Dockerfile.strings
      args:
        rocky: $RL8
